###
POST http://localhost:3003/api/register
Content-Type: application/json

{
    "email": "jan@kowalski.pl",
    "password": "tajnehaslo123"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "email": "jan@kowalski.pl",
    "password": "zlehaslo"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "email": "jan@kowalski.pl",
    "password": "tajnehaslo123"
}